### ISSUE TITLE
RuntimeWarning: divide by zero encountered in divide

### ISSUE THREAD

**Issue by ted-kord** [SageanneS/mitochondria-model-ecc#1]
When I run the model, I get lots of errors with the following messages:

> RuntimeWarning: divide by zero encountered in divide

> RuntimeWarning: invalid value encountered in divide

When I plot t against V, it is just a straight line up and across.

Can you try this and fix this. Thanks.

**Comment by SageanneS** [comment]
A model run file has now been uploaded to the repository that you may use. 
When you plot t against V, you will get the desired result.  
This model run file is titled `run_full_model.py`. 

_This is the model code that was used to generate the results presented in the scientific journal publication: https://link.springer.com/article/10.1007/s11538-022-01079-3. 
**Please remember to cite this article if used for research purposes as per the MIT Licensing Agreement._**

The remaining repository files have been moved to the folder `dev`. These files are a WIP on refactoring and are not required for simulating the model just posted. 

Thanks

**Comment by ted-kord** [comment]
Thank you
